services:

  pwned-proxy-app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile.prod
    env_file: .env
    expose:
      - "8000"
    volumes:
      - static-data:/usr/src/project/staticfiles
    depends_on:
      - pwned-proxy-db

  pwned-proxy-nginx:
    image: nginx:stable-alpine
    depends_on:

      - pwned-proxy-app

    ports:
      - "80:80"
      - "81:81"
    volumes:
      - "./.devcontainer/nginx.conf:/etc/nginx/conf.d/default.conf:ro"
      - static-data:/usr/src/project/staticfiles
      - "./.devcontainer/index.html:/usr/share/nginx/html/dummy/index.html:ro"

  pwned-proxy-db:
    image: postgres:16-alpine
    env_file: .env
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
  static-data:
