version: "3.9"

services:
  pwned-proxy-app-main:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CURRENT_UID: ${CURRENT_UID:-1000}
        CURRENT_GID: ${CURRENT_GID:-1000}
    user: "${CURRENT_UID:-1000}:${CURRENT_GID:-1000}"
    command: sleep infinity
    stdin_open: true
    tty: true
    volumes:
      - ..:/usr/src/project
    environment:
      GIT_USER_NAME: ${GIT_USER_NAME:-user}
      GIT_USER_EMAIL: ${GIT_USER_EMAIL:-user@example.com}
      DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@pwned-proxy-db:5432/pwned_proxy_db
    depends_on:
      - pwned-proxy-db

  pwned-proxy-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - pwned-proxy-db

volumes:
  postgres-data:
  pgadmin-data:
